on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot Project Upload Action
        uses: hs project upload --forceCreate --use-env
        with:
          account_id: ${{ vars.hubspot_account_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}