on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v2.0.1
        with:
          src_dir: src
          dest_dir: demo-theme
          account_id: ${{ vars.HUBSPOT_ACCOUNT_ID }}
          personal_access_key: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}